name: Orbitez Staging CD

on:
  push:
    branches:
    - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  deploy:
    name: Deployment to staging
    runs-on: ubuntu-latest
    steps:
    - name: Deploying to staging via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ./orbitez-staging/orbitez-secret/
          git reset --hard
          git pull https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/stepandra/orbitez-secret.git
          git fetch --prune
          cd ./orbitez
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh
          nvm use --lts=gallium
          npm i
          npm run build &&
          pm2 reload Orbitez-staging
          cd ../server
          yarn
          pm2 reload Orbitez-staging-server
